scripts: Rename environment variables from CLANG_GNOME* to GNOME_CLANG*
Let’s not tread on the Clang namespace. This also makes everything
consistently use gnome-clang, so nobody has to remember which thing uses
gnome-clang and which uses clang-gnome.

diff --git a/scripts/gnome-clang b/scripts/gnome-clang
--- a/scripts/gnome-clang
+++ b/scripts/gnome-clang
@@ -3,16 +3,16 @@
 clang_bin_dir=`dirname "$0"`
 clang_prefix="$clang_bin_dir/.."
 
-# Try and find the real Clang executable. $CLANG_GNOME_CC trumps everything.
+# Try and find the real Clang executable. $GNOME_CLANG_CC trumps everything.
 # Otherwise assume clang is in the same directory as this script.
-if [ "x$CLANG_GNOME_CC" != "x" ]; then
-	real_clang="$CLANG_GNOME_CC"
+if [ "x$GNOME_CLANG_CC" != "x" ]; then
+	real_clang="$GNOME_CLANG_CC"
 elif [ -f "$clang_prefix/bin/clang" ]; then
 	real_clang="$clang_prefix/bin/clang"
 elif [ -f /usr/bin/clang ]; then
 	real_clang=/usr/bin/clang
 else
-	echo "Error: Could not find clang executable. Set CLANG_GNOME_CC to the absolute path of the real clang executable." >& 2
+	echo "Error: Could not find clang executable. Set GNOME_CLANG_CC to the absolute path of the real clang executable." >& 2
 fi
 
 # Extract the clang version.
@@ -22,15 +22,15 @@ fi
 #     Thread model: posix
 clang_version=`"$real_clang" --version | head -n1 | cut -f3 -d ' '`
 
-# Try and find the gnome-clang plugin. $CLANG_GNOME_PLUGIN trumps everything.
-if [ "x$CLANG_GNOME_PLUGIN" != "x" ]; then
-	plugin_path="$CLANG_GNOME_PLUGIN"
+# Try and find the gnome-clang plugin. $GNOME_CLANG_PLUGIN trumps everything.
+if [ "x$GNOME_CLANG_PLUGIN" != "x" ]; then
+	plugin_path="$GNOME_CLANG_PLUGIN"
 elif [ -f "$clang_prefix/lib64/gnome-clang/$clang_version/libclang-gnome.so" ]; then
 	plugin_path="$clang_prefix/lib64/gnome-clang/$clang_version/libclang-gnome.so"
 elif [ -f "$clang_prefix/lib/gnome-clang/$clang_version/libclang-gnome.so" ]; then
 	plugin_path="$clang_prefix/lib/gnome-clang/$clang_version/libclang-gnome.so"
 else
-	echo "Error: Could not find libclang-gnome.so. Set CLANG_GNOME_PLUGIN to the absolute path of the gnome-clang plugin." >& 2
+	echo "Error: Could not find libclang-gnome.so. Set GNOME_CLANG_PLUGIN to the absolute path of the gnome-clang plugin." >& 2
 fi
 
 plugin_name=gnome
@@ -44,5 +44,5 @@ exec "$real_clang" \
 	"$first_arg" \
 	-load "$plugin_path" \
 	-add-plugin "$plugin_name" \
-	$CLANG_GNOME_CFLAGS \
+	$GNOME_CLANG_CFLAGS \
 	"$@"
